### ISSUE TITLE
Value estimates and true values

### ISSUE THREAD

**Issue by flmdaybreak** [ling-pan/SD3#1]
作者您好！非常感谢您的代码，请问论文中   stimation of value functions is shown in Figure 4(a), where value estimates are averaged over 1000 states sampled from the replay buffer at each timestep, and true values are estimated by averaging the discounted long-term rewards obtained by rolling out the current policy starting from the sampled states at each timestep. 随机抽取1000个states在计算对应的true values时，将gym中的游戏环境指定初始化为对应的state，请问这一步是通过修改gym游戏环境中的源码来实现游戏状态的指定初始化吗？

**Comment by ling-pan** [comment]
你好，是的，true values的估计需要将环境的初始状态设置为对应的state。

**Comment by flmdaybreak** [comment]
> 你好，是的，true values的估计需要将环境的初始状态设置为对应的state。

多谢作者回复

**Comment by LQNew** [comment]
Hi, all! I have noticed that the author mentioned the computation of true values. I have no idea how to change gym code to fit this need. So, I hope the author can release the code of this part !! If it is not convenient, I can also communicate with the author through email. I look forward for your reply. By the way, thx for your open-source code  and happy new year!

**Comment by ling-pan** [comment]
Hi, you can do it by accessing the state through the simulator in MuJoCo in a similar way as in [https://github.com/openai/gym/issues/1617](url).
